container:
  image: archlinux:base-devel
  cpu: 4
  memory: 8G
  privileged: true
  volumes:
    - name: dockersock
      path: /var/run/docker.sock

build_task:
  preparation_script:
    - sudo mkdir /test
    - sudo mkdir /test/proc
    - sudo mount -t proc /proc /test/proc
    - sudo mount -t sysfs /sys /test/sys
    - sudo chroot /test /bin/bash
    - ls
    - ls /
