container:
  image: archlinux:base-devel
  cpu: 8
  memory: 12G
  privileged: true
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
env:
  LFS: /mnt

build_task:
  preparation_script:
    - pacman -Suy --noconfirm bash binutils bison coreutils diffutils gawk gcc grep gzip m4 make patch perl python sed tar texinfo xz wget
    - mkdir -pv $LFS
    - mkdir -v $LFS/sources
    - chmod -v a+wt $LFS/sources
    - wget https://www.linuxfromscratch.org/lfs/view/stable-systemd/wget-list-systemd
    - sed -i 's#https://prdownloads.sourceforge.net/expat/expat-2.6.0.tar.xz#https://prdownloads.sourceforge.net/expat/2.6.0/expat-2.6.0-RENAMED-VULNERABLE-PLEASE-USE-2.6.2-INSTEAD.tar.xz#g' wget-list-systemd
    - wget --input-file=wget-list-systemd --continue --directory-prefix=$LFS/sources
    - wget https://www.linuxfromscratch.org/lfs/view/stable-systemd/md5sums --directory-prefix=$LFS/sources/
    - sed -i 's#expat-2.6.0.tar.xz#expat-2.6.0-RENAMED-VULNERABLE-PLEASE-USE-2.6.2-INSTEAD.tar.xz#g' $LFS/sources/md5sums
    - pushd $LFS/sources
    -   md5sum -c md5sums
    - popd
    - chown root:root $LFS/sources/*
    - mkdir -pv $LFS/{etc,var} $LFS/usr/{bin,lib,sbin}
    - for i in bin lib sbin; do
    -   ln -sv usr/$i $LFS/$i
    - done
    - case $(uname -m) in
    -   x86_64) mkdir -pv $LFS/lib64 ;;
    - esac
    - mkdir -pv $LFS/tools
    - groupadd lfs
    - useradd -s /bin/bash -g lfs -m -k /dev/null lfs
    - chown -v lfs $LFS/{usr{,/*},lib,var,etc,bin,sbin,tools}
    - case $(uname -m) in
    -   x86_64) chown -v lfs $LFS/lib64 ;;
    - esac
  build_temporary_tools_script:
    - su - lfs
    - set +h
    - umask 022
    - LFS=/mnt
    - LC_ALL=POSIX
    - LFS_TGT=$(uname -m)-lfs-linux-gnu
    - PATH=/usr/bin
    - if [ ! -L /bin ]; then PATH=/bin:$PATH; fi
    - PATH=$LFS/tools/bin:$PATH
    - CONFIG_SITE=$LFS/usr/share/config.site
    - MAKEFLAGS=-j$(nproc)
    - export MAKEFLAGS LFS LC_ALL LFS_TGT PATH CONFIG_SITE
    - cd $LFS/sources
    - tar -xf binutils-2.42.tar.xz # Binutils-2.42 - Pass 1
    - pushd binutils-2.42
    -   mkdir -v build
    -   cd       build
    -   ../configure --prefix=$LFS/tools
          --with-sysroot=$LFS
          --target=$LFS_TGT
          --disable-nls
          --enable-gprofng=no
          --disable-werror
          --enable-default-hash-style=gnu
    -   make
    -   make install
    - popd
    - rm -rf binutils-2.42
    - tar -xf gcc-13.2.0.tar.xz # GCC-13.2.0 - Pass 1
    - pushd gcc-13.2.0
    -   tar -xf ../mpfr-4.2.1.tar.xz
    -   mv -v mpfr-4.2.1 mpfr
    -   tar -xf ../gmp-6.3.0.tar.xz
    -   mv -v gmp-6.3.0 gmp
    -   tar -xf ../mpc-1.3.1.tar.gz
    -   mv -v mpc-1.3.1 mpc
    -   case $(uname -m) in
    -     x86_64)
    -       sed -e '/m64=/s/lib64/lib/'
              -i.orig gcc/config/i386/t-linux64
    -     ;;
    -   esac
    -   mkdir -v build
    -   cd       build
    -   ../configure
          --target=$LFS_TGT
          --prefix=$LFS/tools
          --with-glibc-version=2.39
          --with-sysroot=$LFS
          --with-newlib
          --without-headers
          --enable-default-pie
          --enable-default-ssp
          --disable-nls
          --disable-shared
          --disable-multilib
          --disable-threads
          --disable-libatomic
          --disable-libgomp
          --disable-libquadmath
          --disable-libssp
          --disable-libvtv
          --disable-libstdcxx
          --enable-languages=c,c++
    -   make
    -   make install
    -   cd ..
    -   cat gcc/limitx.h gcc/glimits.h gcc/limity.h >
          `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include/limits.h
    - popd
    - rm -rf gcc-13.2.0
    - tar -xf linux-6.7.4.tar.xz # Linux-6.7.4 API Headers
    - pushd linux-6.7.4
    -   make mrproper
    -   make headers
    -   find usr/include -type f ! -name '*.h' -delete
    -   cp -rv usr/include $LFS/usr
    - popd
    - rm -rf linux-6.7.4
    - tar -xf glibc-2.39.tar.xz # Glibc-2.39
    - pushd glibc-2.39
    -   case $(uname -m) in
    -     i?86)   ln -sfv ld-linux.so.2 $LFS/lib/ld-lsb.so.3
    -     ;;
    -     x86_64) ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64
    -       ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64/ld-lsb-x86-64.so.3
    -     ;;
    -   esac
    -   patch -Np1 -i ../glibc-2.39-fhs-1.patch
    -   mkdir -v build
    -   cd       build
    -   echo "rootsbindir=/usr/sbin" > configparms
    -   ../configure
          --prefix=/usr
          --host=$LFS_TGT
          --build=$(../scripts/config.guess)
          --enable-kernel=4.19
          --with-headers=$LFS/usr/include
          --disable-nscd
          libc_cv_slibdir=/usr/lib
    -   make
    -   make DESTDIR=$LFS install
    -   sed '/RTLDLIST=/s@/usr@@g' -i $LFS/usr/bin/ldd
    # -   echo 'int main(){}' | $LFS_TGT-gcc -xc -
    # -   readelf -l a.out | grep ld-linux
    - popd
    - rm -rf glibc-2.39
    - tar -xf gcc-13.2.0.tar.xz # Libstdc++ from GCC-13.2.0
    - pushd gcc-13.2.0
    -   mkdir -v build
    -   cd       build
    -   ../libstdc++-v3/configure
          --host=$LFS_TGT
          --build=$(../config.guess)
          --prefix=/usr
          --disable-multilib
          --disable-nls
          --disable-libstdcxx-pch
          --with-gxx-include-dir=/tools/$LFS_TGT/include/c++/13.2.0
    -   make
    -   make DESTDIR=$LFS install
    -   rm -v $LFS/usr/lib/lib{stdc++{,exp,fs},supc++}.la
    - popd
    - rm -rf gcc-13.2.0
    - tar -xf m4-1.4.19.tar.xz # M4-1.4.19
    - pushd m4-1.4.19
    -   ./configure --prefix=/usr
          --host=$LFS_TGT
          --build=$(build-aux/config.guess)
    -   make
    -   make DESTDIR=$LFS install
    - popd
    - rm -rf m4-1.4.19
    - tar -xf ncurses-6.4-20230520.tar.xz # Ncurses-6.4-20230520
    - pushd ncurses-6.4-20230520
    -   sed -i s/mawk// configure
    -   mkdir build
    -   pushd build
    -     ../configure
    -     make -C include
    -     make -C progs tic
    -   popd
    -   ./configure --prefix=/usr
          --host=$LFS_TGT
          --build=$(./config.guess)
          --mandir=/usr/share/man
          --with-manpage-format=normal
          --with-shared
          --without-normal
          --with-cxx-shared
          --without-debug
          --without-ada
          --disable-stripping
          --enable-widec
    -   make
    -   make DESTDIR=$LFS TIC_PATH=$(pwd)/build/progs/tic install
    -   ln -sv libncursesw.so $LFS/usr/lib/libncurses.so
    -   sed -e 's/^#if.*XOPEN.*$/#if 1/'
        -i $LFS/usr/include/curses.h
    - popd
    - rm -rf ncurses-6.4-20230520
    - tar -xf bash-5.2.21.tar.gz # Bash-5.2.21
    - pushd bash-5.2.21
    -   ./configure --prefix=/usr
          --build=$(sh support/config.guess)
          --host=$LFS_TGT
          --without-bash-malloc
    -   make
    -   make DESTDIR=$LFS install
    -   ln -sv bash $LFS/bin/sh
    - popd
    - rm -rf bash-5.2.21
    - tar -xf coreutils-9.4.tar.xz # Coreutils-9.4
    - pushd coreutils-9.4
    -   ./configure --prefix=/usr
          --host=$LFS_TGT
          --build=$(build-aux/config.guess)
          --enable-install-program=hostname
          --enable-no-install-program=kill,uptime
    -   make
    -   make DESTDIR=$LFS install
    -   mv -v $LFS/usr/bin/chroot              $LFS/usr/sbin
    -   mkdir -pv $LFS/usr/share/man/man8
    -   mv -v $LFS/usr/share/man/man1/chroot.1 $LFS/usr/share/man/man8/chroot.8
    -   sed -i 's/"1"/"8"/'                    $LFS/usr/share/man/man8/chroot.8
    - popd
    - rm -rf coreutils-9.4
    - tar -xf diffutils-3.10.tar.xz # Diffutils-3.10
    - pushd diffutils-3.10
    -   ./configure --prefix=/usr
          --host=$LFS_TGT
          --build=$(./build-aux/config.guess)
    -   make
    -   make DESTDIR=$LFS install
    - popd
    - rm -rf diffutils-3.10
    - tar -xf file-5.45.tar.gz # File-5.45
    - pushd file-5.45
    -   mkdir build
    -   pushd build
    -     ../configure --disable-bzlib
            --disable-libseccomp
            --disable-xzlib
            --disable-zlib
    -     make
    -   popd
    -   ./configure --prefix=/usr --host=$LFS_TGT --build=$(./config.guess)
    -   make FILE_COMPILE=$(pwd)/build/src/file
    -   make DESTDIR=$LFS install
    -   rm -v $LFS/usr/lib/libmagic.la
    - popd
    - rm -rf file-5.45
    - tar -xf findutils-4.9.0.tar.xz # Findutils-4.9.0
    - pushd findutils-4.9.0
    -   ./configure --prefix=/usr
          --localstatedir=/var/lib/locate
          --host=$LFS_TGT
          --build=$(build-aux/config.guess)
    -   make
    -   make DESTDIR=$LFS install
    - popd
    - rm -rf findutils-4.9.0
    - tar -xf gawk-5.3.0.tar.xz # Gawk-5.3.0
    - pushd gawk-5.3.0
    -   sed -i 's/extras//' Makefile.in
    -   ./configure --prefix=/usr
          --host=$LFS_TGT
          --build=$(build-aux/config.guess)
    -   make
    -   make DESTDIR=$LFS install
    - popd
    - rm -rf gawk-5.3.0
    - tar -xf grep-3.11.tar.xz # Grep-3.11
    - pushd grep-3.11
    -   ./configure --prefix=/usr
          --host=$LFS_TGT
          --build=$(./build-aux/config.guess)
    -   make
    -   make DESTDIR=$LFS install
    - popd
    - rm -rf grep-3.11
    - tar -xf gzip-1.13.tar.xz # Gzip-1.13
    - pushd gzip-1.13
    -   ./configure --prefix=/usr --host=$LFS_TGT
    -   make
    -   make DESTDIR=$LFS install
    - popd
    - rm -rf gzip-1.13
    - tar -xf make-4.4.1.tar.gz # Make-4.4.1
    - pushd make-4.4.1
    -   ./configure --prefix=/usr
          --without-guile
          --host=$LFS_TGT
          --build=$(build-aux/config.guess)
    -   make
    -   make DESTDIR=$LFS install
    - popd
    - rm -rf make-4.4.1
    - tar -xf patch-2.7.6.tar.xz # Patch-2.7.6
    - pushd patch-2.7.6
    -   ./configure --prefix=/usr
          --host=$LFS_TGT
          --build=$(build-aux/config.guess)
    -   make
    -   make DESTDIR=$LFS install
    - popd
    - rm -rf patch-2.7.6
    - tar -xf sed-4.9.tar.xz # Sed-4.9
    - pushd sed-4.9
    -   ./configure --prefix=/usr
          --host=$LFS_TGT
          --build=$(./build-aux/config.guess)
    -   make
    -   make DESTDIR=$LFS install
    - popd
    - rm -rf sed-4.9
    - tar -xf tar-1.35.tar.xz # Tar-1.35
    - pushd tar-1.35
    -   ./configure --prefix=/usr
          --host=$LFS_TGT
          --build=$(build-aux/config.guess)
    -   make
    -   make DESTDIR=$LFS install
    - popd
    - rm -rf tar-1.35
    - tar -xf xz-5.4.6.tar.xz # Xz-5.4.6
    - pushd xz-5.4.6
    -   ./configure --prefix=/usr
          --host=$LFS_TGT
          --build=$(build-aux/config.guess)
          --disable-static
          --docdir=/usr/share/doc/xz-5.4.6
    -   make
    -   make DESTDIR=$LFS install
    -   rm -v $LFS/usr/lib/liblzma.la
    - popd
    - rm -rf xz-5.4.6
    - tar -xf binutils-2.42.tar.xz # Binutils-2.42 - Pass 2
    - pushd binutils-2.42
    -   sed '6009s/$add_dir//' -i ltmain.sh
    -   mkdir -v build
    -   cd       build
    -   ../configure
          --prefix=/usr
          --build=$(../config.guess)
          --host=$LFS_TGT
          --disable-nls
          --enable-shared
          --enable-gprofng=no
          --disable-werror
          --enable-64-bit-bfd
          --enable-default-hash-style=gnu
    -   make
    -   make DESTDIR=$LFS install
    -   rm -v $LFS/usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes,sframe}.{a,la}
    - popd
    - rm -rf binutils-2.42.tar.xz
    - tar -xf gcc-13.2.0.tar.xz # GCC-13.2.0 - Pass 2
    - pushd gcc-13.2.0
    -   tar -xf ../mpfr-4.2.1.tar.xz
    -   mv -v mpfr-4.2.1 mpfr
    -   tar -xf ../gmp-6.3.0.tar.xz
    -   mv -v gmp-6.3.0 gmp
    -   tar -xf ../mpc-1.3.1.tar.gz
    -   mv -v mpc-1.3.1 mpc
    -   case $(uname -m) in
    -     x86_64)
    -       sed -e '/m64=/s/lib64/lib/'
              -i.orig gcc/config/i386/t-linux64
    -     ;;
    -   esac
    -   sed '/thread_header =/s/@.*@/gthr-posix.h/'
          -i libgcc/Makefile.in libstdc++-v3/include/Makefile.in
    -   mkdir -v build
    -   cd       build
    -   ../configure
          --build=$(../config.guess)
          --host=$LFS_TGT
          --target=$LFS_TGT
          LDFLAGS_FOR_TARGET=-L$PWD/$LFS_TGT/libgcc
          --prefix=/usr
          --with-build-sysroot=$LFS
          --enable-default-pie
          --enable-default-ssp
          --disable-nls
          --disable-multilib
          --disable-libatomic
          --disable-libgomp
          --disable-libquadmath
          --disable-libsanitizer
          --disable-libssp
          --disable-libvtv
          --enable-languages=c,c++
    -   make
    -   make DESTDIR=$LFS install
    -   ln -sv gcc $LFS/usr/bin/cc
    - popd
    - rm -rf gcc-13.2.0
    - chown -R root:root $LFS/{usr,lib,var,etc,bin,sbin,tools}
    - case $(uname -m) in
    -   x86_64) chown -R root:root $LFS/lib64 ;;
    - exit
    - mkdir -pv $LFS/{dev,proc,sys,run}
    - chroot "$LFS" /usr/bin/env -i
        HOME=/root
        TERM="$TERM"
        PS1='(lfs chroot) \u:\w\$ '
        PATH=/usr/bin:/usr/sbin
        MAKEFLAGS="-j$(nproc)"
        TESTSUITEFLAGS="-j$(nproc)"
        /bin/bash --login
    - mkdir -pv /{boot,home,mnt,opt,srv}
    - mkdir -pv /etc/{opt,sysconfig}
    - mkdir -pv /lib/firmware
    - mkdir -pv /media/{floppy,cdrom}
    - mkdir -pv /usr/{,local/}{include,src}
    - mkdir -pv /usr/local/{bin,lib,sbin}
    - mkdir -pv /usr/{,local/}share/{color,dict,doc,info,locale,man}
    - mkdir -pv /usr/{,local/}share/{misc,terminfo,zoneinfo}
    - mkdir -pv /usr/{,local/}share/man/man{1..8}
    - mkdir -pv /var/{cache,local,log,mail,opt,spool}
    - mkdir -pv /var/lib/{color,misc,locate}
    - ln -sfv /run /var/run
    - ln -sfv /run/lock /var/lock
    - install -dv -m 0750 /root
    - install -dv -m 1777 /tmp /var/tmp
    - cat > /etc/hosts << EOF
    -   127.0.0.1  localhost $(hostname)
    -   ::1        localhost
    - EOF
    - cat > /etc/passwd << "EOF"
    -   root:x:0:0:root:/root:/bin/bash
    -   bin:x:1:1:bin:/dev/null:/usr/bin/false
    -   daemon:x:6:6:Daemon User:/dev/null:/usr/bin/false
    -   messagebus:x:18:18:D-Bus Message Daemon User:/run/dbus:/usr/bin/false
    -   systemd-journal-gateway:x:73:73:systemd Journal Gateway:/:/usr/bin/false
    -   systemd-journal-remote:x:74:74:systemd Journal Remote:/:/usr/bin/false
    -   systemd-journal-upload:x:75:75:systemd Journal Upload:/:/usr/bin/false
    -   systemd-network:x:76:76:systemd Network Management:/:/usr/bin/false
    -   systemd-resolve:x:77:77:systemd Resolver:/:/usr/bin/false
    -   systemd-timesync:x:78:78:systemd Time Synchronization:/:/usr/bin/false
    -   systemd-coredump:x:79:79:systemd Core Dumper:/:/usr/bin/false
    -   uuidd:x:80:80:UUID Generation Daemon User:/dev/null:/usr/bin/false
    -   systemd-oom:x:81:81:systemd Out Of Memory Daemon:/:/usr/bin/false
    -   nobody:x:65534:65534:Unprivileged User:/dev/null:/usr/bin/false
    - EOF
    - cat > /etc/group << "EOF"
    -   root:x:0:
    -   bin:x:1:daemon
    -   sys:x:2:
    -   kmem:x:3:
    -   tape:x:4:
    -   tty:x:5:
    -   daemon:x:6:
    -   floppy:x:7:
    -   disk:x:8:
    -   lp:x:9:
    -   dialout:x:10:
    -   audio:x:11:
    -   video:x:12:
    -   utmp:x:13:
    -   cdrom:x:15:
    -   adm:x:16:
    -   messagebus:x:18:
    -   systemd-journal:x:23:
    -   input:x:24:
    -   mail:x:34:
    -   kvm:x:61:
    -   systemd-journal-gateway:x:73:
    -   systemd-journal-remote:x:74:
    -   systemd-journal-upload:x:75:
    -   systemd-network:x:76:
    -   systemd-resolve:x:77:
    -   systemd-timesync:x:78:
    -   systemd-coredump:x:79:
    -   uuidd:x:80:
    -   systemd-oom:x:81:
    -   wheel:x:97:
    -   users:x:999:
    -   nogroup:x:65534:
    - EOF
    - echo "tester:x:101:101::/home/tester:/bin/bash" >> /etc/passwd
    - echo "tester:x:101:" >> /etc/group
    - install -o tester -d /home/tester
    - exec /usr/bin/bash --login
    - touch /var/log/{btmp,lastlog,faillog,wtmp}
    - chgrp -v utmp /var/log/lastlog
    - chmod -v 664  /var/log/lastlog
    - chmod -v 600  /var/log/btmp
    - tar -cJf /tmp/cirrus-ci-build/mnt.tar.xz /mnt
  binaries_artifacts:
    path: "mnt.tar.xz"