container:
  image: archlinux:base-devel
  cpu: 4
  memory: 8G
env:
  LFS: /mnt

build_task:
  preparation_script:
    - cd /
    - tar -cJf bin.tar.xz bin
  binaries_artifacts:
    path: "/bin.tar.xz"
