container:
  image: archlinux:base-devel
  cpu: 4
  memory: 8G
env:
  LFS: /mnt

build_task:
  preparation_script:
    - cd /
    - tar -cJf /tmp/cirrus-ci-build/bin.tar.xz bin
    - ls /tmp/cirrus-ci-build/
  binaries_artifacts:
    path: "bin.tar.xz"
