container:
  image: archlinux:base-devel
  cpu: 8
  memory: 32G

build_task:
  preparation_script:
    - pacman -Suy --noconfirm bash binutils bison coreutils diffutils gawk gcc grep gzip m4 make patch perl python sed tar texinfo xz wget
    - export LFS=/mnt
    - mkdir -pv $LFS
    - mkdir -v $LFS/sources
    - chmod -v a+wt $LFS/sources
    - wget https://www.linuxfromscratch.org/lfs/view/stable-systemd/wget-list-systemd
    - sed -i 's#https://prdownloads.sourceforge.net/expat/expat-2.6.0.tar.xz#https://prdownloads.sourceforge.net/expat/2.6.0/expat-2.6.0-RENAMED-VULNERABLE-PLEASE-USE-2.6.2-INSTEAD.tar.xz#g' wget-list-systemd
    - wget --input-file=wget-list-systemd --continue --directory-prefix=$LFS/sources
    - wget https://www.linuxfromscratch.org/lfs/view/stable-systemd/md5sums $LFS/sources/
    - pushd $LFS/sources
    -   md5sum -c md5sums
    - popd
    - chown root:root $LFS/sources/*
    - mkdir -pv $LFS/{etc,var} $LFS/usr/{bin,lib,sbin}
    - for i in bin lib sbin; do
    -   ln -sv usr/$i $LFS/$i
    - done
    - for i in bin lib sbin; do
    -   ln -sv usr/$i $LFS/$i
    - done
    - mkdir -pv $LFS/tools
    - groupadd lfs
    - useradd -s /bin/bash -g lfs -m -k /dev/null lfs
    - chown -v lfs $LFS/{usr{,/*},lib,var,etc,bin,sbin,tools}
    - case $(uname -m) in
    -   x86_64) chown -v lfs $LFS/lib64 ;;
    - esac
    - su - lfs
    - cat > ~/.bash_profile << "EOF"
    -   exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' /bin/bash
    - EOF
    - cat > ~/.bashrc << "EOF"
    - set +h
    - umask 022
    - LFS=/mnt/lfs
    - LC_ALL=POSIX
    - LFS_TGT=$(uname -m)-lfs-linux-gnu
    - PATH=/usr/bin
    - if [ ! -L /bin ]; then PATH=/bin:$PATH; fi
    - PATH=$LFS/tools/bin:$PATH
    - CONFIG_SITE=$LFS/usr/share/config.site
    - export LFS LC_ALL LFS_TGT PATH CONFIG_SITE
    - EOF
    - export MAKEFLAGS=-j8
    - cat >> ~/.bashrc << "EOF"
    -  export MAKEFLAGS=-j$(nproc)
    - EOF
    - source ~/.bash_profile
    - cd $LFS/sources
    - tar -xJf binutils*-tar.xz
    - cd binutils*
    - mkdir -v build
    - cd       build
    - ../configure --prefix=$LFS/tools \
        --with-sysroot=$LFS \
        --target=$LFS_TGT   \
        --disable-nls       \
        --enable-gprofng=no \
        --disable-werror    \
        --enable-default-hash-style=gnu
    - make
    - make install
    - cd ../
    - rm -rf binutils*
    - tar -xJf gcc*-tar.xz
    - cd gcc*
    - tar -xf ../mpfr-4.2.1.tar.xz
    - mv -v mpfr-4.2.1 mpfr
    - tar -xf ../gmp-6.3.0.tar.xz
    - mv -v gmp-6.3.0 gmp
    - tar -xf ../mpc-1.3.1.tar.gz
    - mv -v mpc-1.3.1 mpc
    - case $(uname -m) in
    -   x86_64)
    -     sed -e '/m64=/s/lib64/lib/' \
            -i.orig gcc/config/i386/t-linux64
    -   ;;
    - esac
    - mkdir -v build
    - cd       build
     ../configure                  \
       --target=$LFS_TGT         \
       --prefix=$LFS/tools       \
       --with-glibc-version=2.39 \
       --with-sysroot=$LFS       \
       --with-newlib             \
       --without-headers         \
       --enable-default-pie      \
       --enable-default-ssp      \
       --disable-nls             \
       --disable-shared          \
       --disable-multilib        \
       --disable-threads         \
       --disable-libatomic       \
       --disable-libgomp         \
       --disable-libquadmath     \
       --disable-libssp          \
       --disable-libvtv          \
       --disable-libstdcxx       \
       --enable-languages=c,c++
    - make
    - make install
    - cd ..
    - cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
       `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include/limits.h
    - cd $LFS/sources
    - rm -rf gcc*
    - tar -xJf linux-*.tar.xz
    - cd linux*
    - make mrproper
    - make headers
    - find usr/include -type f ! -name '*.h' -delete
    - cp -rv usr/include $LFS/usr
    - cd ../
    - rm -rf linux*
    - tar -xJf glibc-*.tar.xz
    - cd glibc*
    - case $(uname -m) in
    -   i?86)   ln -sfv ld-linux.so.2 $LFS/lib/ld-lsb.so.3
    -   ;;
    -   x86_64) ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64
    -           ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64/ld-lsb-x86-64.so.3
    -   ;;
    - esac
    - patch -Np1 -i ../glibc-2.39-fhs-1.patch
    - mkdir -v build
    - cd       build
    - echo "rootsbindir=/usr/sbin" > configparms
    - ../configure                             \
        --prefix=/usr                      \
        --host=$LFS_TGT                    \
        --build=$(../scripts/config.guess) \
        --enable-kernel=4.19               \
        --with-headers=$LFS/usr/include    \
        --disable-nscd                     \
        libc_cv_slibdir=/usr/lib
    - make
    - make DESTDIR=$LFS install
    - sed '/RTLDLIST=/s@/usr@@g' -i $LFS/usr/bin/ldd
    - echo 'int main(){}' | $LFS_TGT-gcc -xc -
    - readelf -l a.out | grep ld-linux
    - cd ../
    - rm -rf glibc*
    - tar -xJf gcc*-tar.xz
    - cd gcc*
    - mkdir -v build
    - cd       build
    - ../libstdc++-v3/configure           \
        --host=$LFS_TGT                 \
        --build=$(../config.guess)      \
        --prefix=/usr                   \
        --disable-multilib              \
        --disable-nls                   \
        --disable-libstdcxx-pch         \
        --with-gxx-include-dir=/tools/$LFS_TGT/include/c++/13.2.0
    - make
    - make DESTDIR=$LFS install
    - rm -v $LFS/usr/lib/lib{stdc++{,exp,fs},supc++}.la
    - cd ../
    - rm -rf gcc*