container:
  image: archlinux:base-devel
  cpu: 4
  memory: 8G
  privileged: true
  volumes:
    - name: dockersock
      path: /var/run/docker.sock

build_task:
  preparation_script:
    - sudo mkdir /test
    - mkdir -pv /test/{dev,proc,sys,run}
    - mount -v --bind /dev /test/dev
